### ISSUE TITLE
Default content in hyper-yield

### ISSUE THREAD

**Issue by t0ggah** [hyperoslo/hyper-content-for-angular#15]
The hyper-yield tag content should be transcluded with no matching hyper-content tag.

This should return `<h2>Default header</h2>`:

``` html
<hyper-yield from="header">
  <h2>Default header</h2>
</hyper-yield>
```

**Comment by sindrenm** [comment]
Neat idea! Pretty much like ui-router does it when you're not in a sub-state. I like it! :+1:

**Comment by sindrenm** [comment]
I think I want this for 1.0.0.
