### ISSUE TITLE
What about when a view changes but content doesn't?

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/hyper-content-for-angular#34]
I came across a scenario here where I'm using hyper-content-for to alter the content of a toolbar from [angular-material](http://material.angular.com). In my layout, I have tihs:

```
<hyper-yield to="toolbar"></hyper-yield>
<span flex></span>
<hyper-yield to="toolbar-right"></hyper-yield>
```

What this does is essentially yield stuff from “toolbar” to the left of the toolbar and stuff in “toolbar-right” at the right, being pushed by the span that takes up unused space. This works great. However, not every view has got content at the right of the toolbar. Of course, when content has been placed at the right once, it will stay in the HYPER_CONTENT_FOR_IDS hash, as we never remove anything from there, which results in the content being visible where it should not be. That was weirdly explained, here are some screenshots:

At first, I'm at an index page that displays one element. There is currently no content in `HYPER_CONTENT_FOR_IDS['toolbar-right']`, so nothing is shown to the right:

![screenshot from 2015-03-28 18-37-11](https://cloud.githubusercontent.com/assets/386122/6882065/a33e6a88-d579-11e4-8c2b-444c3a3079c6.png)

Then, I click on that element to see details. This page has two buttons at the right of the toolbar, and thus `HYPER_CONTENT_FOR_IDS['toolbar-right']` will now have some content:

![screenshot from 2015-03-28 18-37-32](https://cloud.githubusercontent.com/assets/386122/6882067/a341b88c-d579-11e4-8cc8-af2102390e17.png)

After going back to the index page, the content will still be in `HYPER_CONTENT_FOR_IDS['toolbar-right']`, hence it will be wrongfully placed in the right hand side of the toolbar:

![screenshot from 2015-03-28 18-38-03](https://cloud.githubusercontent.com/assets/386122/6882066/a341174c-d579-11e4-9d13-505239bc21b7.png)

Now, I see two obvious ways of dealing with this issue. One would be to empty all content in HYPER_CONTENT_FOR_IDS on every new route change, which I assume would require us to hook into the router that is being used for the application, which again would require some configuration from the user as we do not know which router that would be.

A second approach would be to require the user to always have a `hyper-content` tag per `hyper-yield` in each of their templates. This also sounds kinda tedious for the user.

Are there any other approaches? How do you guys think we should handle this problem?

**Comment by timkurvers** [comment]
Wouldn't you be able to nullify the content yourself on the index?

**Comment by sindrenm** [comment]
Yeah, that would essentially be the same as creating an empty `hyper-content` tag on the index page, right?

**Comment by jgorset** [comment]
I think what @timkurvers said makes sense, but it _feels_ like a workaround for a bug to me. If we require a `hyper-content` tag at least that will never happen, but people will probably be annoyed that they need to add bloat for no apparent reason.

I think I like the first option the most, but maybe we could make it flexible so it can be just any callback and not specifically from a router (though that will probably mostly always be the case).

**Comment by fespinoza** [comment]
i run into the same issue while working with this component on a project

i agree the best solution is:

> to clear the content when the route changes

on the implementation side, i guess we can handle this on the different events the routers use or trying to "watch" the current url

**Comment by sindrenm** [comment]
But how would you do that, though, @fespinoza, without knowing what router is being used in the application?
