### ISSUE TITLE
Prefix directives with hyper

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/hyper-content-for-angular#4]
The directives are now called `content` and `yield`, which might cause naming conflicts later. They should be renamed to `hyp-content` and `hyp-yield`, respectively.

**Comment by jgorset** [comment]
I DISAGREE WITH DIS

**Comment by sindrenm** [comment]
Well, it certainly reads better without the prefixes, but to avoid potential naming clashes, a prefix is nice. Core libraries prefix every directive with `ng-` and ngMaterial prefixes every directive with `md-`. I think we should abide by the conventions and prefix our directives as well.

**Comment by sindrenm** [comment]
Reopening this until we figure it out entirely.

**Comment by jgorset** [comment]
Or do both, as per @timkurvers' idea.

**Comment by jgorset** [comment]
For future reference: http://stackoverflow.com/questions/18753081/check-if-an-angular-directive-exists

**Comment by sindrenm** [comment]
If we can figure out how to do that.

**Comment by jgorset** [comment]
Right.

**Comment by sindrenm** [comment]
And yes, that does tell you how to figure out if a directive exists. After creating the directive. Question is if we then can rename the directive that we just created. :wink:

**Comment by jgorset** [comment]
If we just define both, in the case of a conflict, won't the user be able to choose which one he wants to take precedence by just loading them in the right order?

**Comment by timkurvers** [comment]
No need to rename? Just add the `content` alias if not taken, or would that be troublesome?

**Comment by sindrenm** [comment]
Not entirely sure about how load order works here. It might be that Angular errors out if there are name clashes. Not sure, though.

**Comment by sindrenm** [comment]
If we were to check whether a directive exists before we create it, we might be able to do so during the config phase. After that I think we're pretty much stuck with what we have already defined. However, if we can use the $injector there to see if a “contentDirectiveProvider” is available, then we're one step closer to solving this, methinks.

**Comment by sindrenm** [comment]
Then again, I don't think we'd have access to the $injector during the config phase, only the $injectorProvider, so that's not gonna work.

**Comment by mathiasbno** [comment]
This still seems super complicated just to have a different naming scheme. Just saying #hypContent

**Comment by sindrenm** [comment]
It's probably kinda complicated. But if we can find a good way to do this, we might also be able to make a separate module that handles this through an easier API during the config phase. :smiley:

**Comment by sindrenm** [comment]
So, what you might not know, people, is that we can also use a colon as a namespace separator (this is built in to Angular). So the exact same code can be used like this:

``` html
<hyp:content for="header">
  Header stuff!
</hyp:content>
```

Is that better? It looks a lot more Kevin Namespace-y.

**Comment by mathiasbno** [comment]
I approve, what do you think gorset:johannes?

**Comment by sindrenm** [comment]
How you like them namespaces?

**Comment by sindrenm** [comment]
However, I do not approve. I think the dash syntax reads better and feels more familiar. Also this is in the docs:

![screen shot 2015-03-18 at 09 35 09](https://cloud.githubusercontent.com/assets/386122/6705162/1dcd672a-cd52-11e4-9c14-910de8d1a1c6.png)

**Comment by sindrenm** [comment]
It also says this:

![screen shot 2015-03-18 at 09 37 18](https://cloud.githubusercontent.com/assets/386122/6705192/6a0d7094-cd52-11e4-8e6c-31f4062d6470.png)

**Comment by sindrenm** [comment]
So I think we just won, @mathiasbno.

**Comment by jgorset** [comment]
Oh my god why.

**Comment by jgorset** [comment]
HTML _SEVEN_? That's in, like, 2050.

**Comment by jgorset** [comment]
How is `:` syntax legacy?

**Comment by sindrenm** [comment]
Because it was the old syntax that was used before it became legacy.

**Comment by sindrenm** [comment]
For reference, this is where the screenshots are from:

https://docs.angularjs.org/guide/directive

**Comment by jgorset** [comment]
> Because it was the old syntax that was used before it became legacy.

![http://i.imgur.com/aNXqGNT.gif](http://i.imgur.com/aNXqGNT.gif)

**Comment by jgorset** [comment]
Can we at least do `hyper`?

**Comment by mathiasbno** [comment]
Knock yourself out! As long as its a prefix :smile:

**Comment by jgorset** [comment]
`mathiasbro-content`

**Comment by sindrenm** [comment]
I'm all up for using “hyper”. Then we'll do that for future modules as well.

**Comment by jgorset** [comment]
:+1:
